// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/achernyak/cellar/design
// --out=$(GOPATH)/src/github.com/achernyak/cellar
// --version=v1.1.0-dirty
//
// API "cellar": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
